import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
// import Sidebar from "@/components/common/Sidebar";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import { fetcher } from "@/lib/fetcher";
import { Toaster } from "sonner";
import BottomNav from "@/components/common/BottomNav";
import Sidebar2 from "@/components/common/Sidebar2";

const jost = Jost({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const navItems: any = await fetcher("/categories");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const settings: any = await fetcher(`/settings`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const contact: any = await fetcher(`/contact`);
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body
        className={`${jost.className} flex bg-background overflow-x-hidden`}
      >
        <div className="hidden md:flex">
          {/* <Sidebar
            contact={contact}
            settings={settings}
            navItems={navItems?.data}
          /> */}
          <Sidebar2 settings={settings} contact={contact} />
        </div>
        <BottomNav />
        <Header />
        <main className="transition-all justify-center md:mx-auto mt-16 md:mt-20 md:ml-56 w-full">
          {children}
          {modal}
          <Toaster position="bottom-right" richColors />
          <Footer />
        </main>
      </body>
    </html>
  );
}
